# Generated by Django 3.2.17 on 2023-05-05 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='username:')),
                ('password', models.CharField(max_length=64, verbose_name='password:')),
                ('step', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='./upload_files')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit.user')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=64, null=True, verbose_name='Host:')),
                ('port', models.IntegerField(null=True, verbose_name='Port:')),
                ('username', models.CharField(max_length=128, null=True, verbose_name='User:')),
                ('password', models.CharField(max_length=128, null=True, verbose_name='Password:')),
                ('database', models.CharField(max_length=128, null=True, verbose_name='Databases:')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_data_source', to='submit.user')),
            ],
        ),
    ]
