# Generated by Django 3.2.17 on 2023-05-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0003_logicalbug'),
    ]

    operations = [
        migrations.AddField(
            model_name='logicalbug',
            name='is_display',
            field=models.BooleanField(default=False),
        ),
    ]
