# Generated by Django 3.2.17 on 2023-05-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0005_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='query_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='query_type_num',
            field=models.IntegerField(default=0),
        ),
    ]
