# Generated by Django 3.2.17 on 2023-05-09 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0006_auto_20230509_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logicalbug',
            name='execution_plan',
        ),
    ]
