# Generated by Django 3.2.17 on 2023-05-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0010_alter_statistics_break_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='break_point',
            field=models.CharField(default='0/0', max_length=32),
        ),
    ]
