# Generated by Django 3.2.17 on 2023-05-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0011_alter_statistics_break_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='status',
            field=models.CharField(default='None', max_length=32),
        ),
    ]
