# Generated by Django 3.2.17 on 2023-05-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0012_statistics_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='status',
            field=models.CharField(default='none', max_length=32),
        ),
    ]
