# Generated by Django 4.2.3 on 2023-08-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0013_alter_statistics_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logicalbug',
            name='minimal_execution_plan',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='logicalbug',
            name='operator',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='logicalbug',
            name='original_execution_plan',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
