# Generated by Django 4.2.3 on 2023-08-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submit", "0014_alter_logicalbug_minimal_execution_plan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="logicalbug",
            name="sqlfile",
            field=models.TextField(default=True),
        ),
    ]
